name: Docker Login to OCI Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  login-to-ocir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Install OCI CLI
#        run: |
#          python3 pip install oci-cli

      - name: Get OCI Auth Token and Log into OCIR
        run: |
          echo "Getting OCI token..."
          # Retrieve token dynamically from OCI CLI
          token=$(oci raw-request --region iad --profile DEFAULT --auth security_token --http-method GET --target-uri "https://iad.ocir.io/20180419/docker/token" | jq -r .data.token)
          echo "$token" | docker login -u 'BEARER_TOKEN' --password-stdin iad.ocir.io

      - name: Pull and Tag Docker Image
        run: |
          docker pull oraclelinux:8-slim
          docker tag "oraclelinux:8-slim" "${{ secrets.OCI_REPOSITORY_PATH }}:8-slim"

      - name: Push Docker Image to OCIR
        run: |
          docker push "${{ secrets.OCI_REPOSITORY_PATH }}:8-slim"
