name: OCI Docker Build and Deploy
on:
  push:
    branches:
      master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OCI CLI
        run: |
          python3 pip install oci-cli

      - name: Configure OCI CLI with Security Token
        run: |
          mkdir -p ~/.oci
          # Write the OCI configuration file
          echo "${{ secrets.OCI_CONFIG }}" > ~/.oci/config
          # Write the raw security token to the token file
          echo "${{ secrets.OCI_SECURITY_TOKEN }}" > ~/.oci/token
          chmod 600 ~/.oci/config ~/.oci/token

      - name: Authenticate with OCI Registry
        run: |
          echo "${{ secrets.OCI_SECURITY_TOKEN }}" | docker login -u "${{ secrets.OCI_USERNAME }}" --password-stdin ${{ secrets.OCI_REGION }}.ocir.io
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/${{ secrets.OCI_REPO }}:latest .

      - name: Push Docker Image to OCIR
        run: |
          docker push ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/${{ secrets.OCI_REPO }}:latest