name: OCI Docker Build and Push
on:
  push:
    branches:
      master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OCI CLI
        run: | 
          python3 -m pip install oci-cli
  # Optionally, specify a specific version

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: OCI Authentication and Docker Login
        run: |
          # Fetch token from OCI registry using oci raw-request
          RESPONSE=$(oci raw-request --region iad --profile DEFAULT --auth security_token --http-method GET --target-uri "https://iad.ocir.io/20180419/docker/token")
          echo "Raw Response: $RESPONSE"
          # Use jq to extract the token and login to Docker
          TOKEN=$(echo $RESPONSE | jq -r .data.token)
          echo "Token: $TOKEN"
          echo $TOKEN | docker login -u BEARER_TOKEN --password-stdin http://iad.ocir.io
      - name: Build Docker Image
        run: |
          docker build -t iad.ocir.io/${{ secrets.OCI_NAMESPACE }}/${{ secrets.OCI_REPO_NAME }}:latest .

      - name: Push Docker Image
        run: |
          docker push iad.ocir.io/${{ secrets.OCI_NAMESPACE }}/${{ secrets.OCI_REPO_NAME }}:latest

      - name: Update or Invoke Function (Optional)
        run: |
          # Add any commands to invoke or update functions if necessary
          echo "Function update/invoke step here"