name: CI/CD Pipeline for OCI Function

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  # Job to build the Docker image
  build_image:
    runs-on: ubuntu-latest  # Use a default runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest .
          docker tag iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:${GITHUB_SHA}

  # Job to push the Docker image to OCI Container Registry
  push_image:
    runs-on: ubuntu-latest  # Use a default runner
    needs: build_image  # This job depends on the completion of 'build_image'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to OCI Container Registry
        run: |
          echo "${OCI_SECURITY_TOKEN}" | oci --auth security_token --security-token login iad.ocir.io
      - name: Push Docker image to OCI Container Registry
        run: |
          echo "Pushing Docker image to OCI Container Registry..."
          docker push iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest
          docker push iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:${GITHUB_SHA}

  # Job to deploy the image to an existing OCI Function
  deploy_function:
    runs-on: ubuntu-latest  # Use a default runner
    needs: push_image  # This job depends on the completion of 'push_image'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up OCI CLI
        uses: oracle-actions/setup-oci-cli@v1
      - name: Update Docker image for OCI Function
        run: |
          echo "Updating Docker image for existing OCI Function..."
          oci fn function update --compartment-id ocid1.compartment.oc1..aaaaaaaai7lpqrjb65oxp7yot4cdlgahobld5xpizdyjyaoef2tjunipxhpa --function-id ocid1.fnfunc.oc1.iad.aaaaaaaajmotp4ycz5pms3y4q3zqdxra6fyg53fxu2ap36yvqoglkbjwxmka --image iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest
      - name: Create or update HTTP trigger for OCI Function
        run: |
          echo "Creating or updating HTTP trigger for function..."
          oci fn trigger create \
            --compartment-id ocid1.compartment.oc1..aaaaaaaai7lpqrjb65oxp7yot4cdlgahobld5xpizdyjyaoef2tjunipxhpa \
            --function-id ocid1.fnfunc.oc1.iad.aaaaaaaajmotp4ycz5pms3y4q3zqdxra6fyg53fxu2ap36yvqoglkbjwxmka \
            --name my-http-trigger \
            --type http
      - name: Invoke the OCI Function
        run: |
          echo "Invoking OCI function..."
          oci fn function invoke --function-id ocid1.fnfunc.oc1.iad.aaaaaaaajmotp4ycz5pms3y4q3zqdxra6fyg53fxu2ap36yvqoglkbjwxmka --body '{}'

