name: CI/CD Pipeline to OCI

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the master branch

jobs:
  # Job to build the Docker image
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Verify Docker installation and set up Docker Buildx
      - name: Verify Docker and Install Docker Buildx
        run: |
          docker --version
          docker info
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to OCI Container Registry using the token (for testing)
      - name: Log in to OCI Container Registry
        run: |
          echo "Logging in to OCI Container Registry..."
          echo "eyJraWQiOiJhc3dfaWFkXzE3MTU2NDgwNzIzNzciLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvY2lkMS51c2VyLm9jMS4uYWFhYWFhYWFzd3VhamRrM2ZndGVydzNnZG92dGxqd2gzYzdid2J3dGV2MzRudTZ2Y3d4YmxrN3RhbHlhIiwiaXNzIjoiYXV0aFNlcnZpY2Uub3JhY2xlLmNvbSIsInNhbWxfZnByaW50IjoiNjQ6Mzk6MjQ6ZmM6YmI6MGQ6NDE6ZTg6ZjA6MjM6NWQ6MzU6ODA6Mjg6MjI6ODMiLCJwdHlwZSI6InVzZXIiLCJzZXNzX2V4cCI6Ik1vbiwgMjUgTm92IDIwMjQgMTM6NDc6NDYgVVRDIiwiYXVkIjoib2NpIiwicHN0eXBlIjoibmF0ZiIsInR0eXBlIjoic2FtbGMiLCJleHAiOjE3MzI1MjY3NDIsImlhdCI6MTczMjUyMzE0MiwianRpIjoiYzM5MmI1NGQtOGQ5Ni00Yjk1LWEzMmUtMjY3Mzg1NjQ1YjlmIiwidGVuYW50Ijoib2NpZDEudGVuYW5jeS5vYzEuLmFhYWFhYWFhZ2tiemdnNmxwenJmNDd4enk0cmpveGc0ZGU2bmNmaXEycm5jbWppdWp2eTJoamd4dnppcSIsImlzX2ZlZCI6InRydWUiLCJncnBzIjoiIiwiandrIjoie1wia2lkXCI6XCJJZ25vcmVkXCIsXCJuXCI6XCIwTmx2LW03ZmlBWmo2b2RQc1IxTHRYNUVON0RtMXg4UFprZGtoNjdiRm5IdjJsYXZrQUd4TE94dVVJUVcxNkZVU3ZwNFdSRW1JYjk0OHZQNVNvWmhBVlpkbmk3cEU5TlVGV1pSTHR6a0t5NGkzUUgxNE8za2prbjRIUERUX2RrajNQQ1ZXM0E5bDdfdXNYTkQwRE9yRjBfT0hTdl9KdzJ1bGI0WTFVS3NTQnEwUl82Zk9BMl9panNqU0dXUXZHdzRwM2YySkloSThNbFV5OVVONk9GN2ZpTE1ZSFk3b1Z4SjdtLV9ZZXBvQjNDS2hWTUZ5WGlpU1Q0aWxyZ2c0STVSZUpTTURZN2hrTnZocEU4S0E0Ykkya3pLLU4zUDFJMURfa3FSRDBrSWR0TUNQVERud2ZQTXVPaU1UT0pPMGpTQkJjbnluM2t4a3FvNm5tbTlOU2IyMXdcIixcImVcIjpcIkFRQUJcIixcImt0eVwiOlwiUlNBXCIsXCJ1c2VcIjpudWxsfSJ9.QYrqttK9KaUdJwNN5ucmForBWRe_JnDi0ZUwEop5LMR1HB-SyyXwlRsqMmd_sqw4mxAoodt51TgpgCpdqLyEIU-hOyejHVNqQufO1ctBIEhsSI1wumIsRbGEaS01QNEQWNx-KhEQ1pMXV0yl7WJcjcPm9l1lRG_b96zHJoOprpUbL1YVl2JJrm1IV3Dx-sHodzJA465S7BOLZnQ-5vGqu4xa3uwRZAao6LDLPWA1AxbN3jPOi416hXmy6AFPt0v8p_x51lhGKmtAmHLIEjSsF_skxL87JJvUrkLHTCm8qq21xkh_9bJKRrTTinCPOK11lCeJ09N9aBFy9eI7pSj-_Q" | docker login -u BEARER_TOKEN --password-stdin iad.ocir.io  # Replace 'your-oci-token-here' with your actual token

      # Build Docker image
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest .
          docker tag iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:${{ github.sha }}

      # Verify the image exists locally
      - name: Verify image exists locally
        run: |
          docker images | grep "iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file" || echo "Image not found"

  # Job to push the Docker image to OCI Container Registry
  push_image:
    runs-on: ubuntu-latest
    needs: build_image  # Ensures this runs after build_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up OCI CLI
      - name: Set up OCI CLI
        uses: oracle-actions/setup-oci-cli@v1

      # Log in to OCI Container Registry using the OCI CLI
      - name: Log in to OCI Container Registry using OCI CLI
        run: |
          echo "Logging in to OCI Container Registry using OCI CLI..."
          oci iam auth security_token --token "your-oci-token-here"  # Replace with your actual token for testing

      # Push Docker image to OCI Container Registry
      - name: Push Docker image to OCI Container Registry
        run: |
          echo "Pushing Docker image to OCI Container Registry..."
          docker push iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest
          docker push iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:${{ github.sha }}
