version: '1.0'

name: CI/CD Pipeline for OCI Function

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  # Job to build the Docker image
  build_image:
    docker:
      image: docker:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "Building Docker image..."
      - docker build -t iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest .
      - docker tag iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:${CI_COMMIT_SHA}

  # Job to push the Docker image to OCI Container Registry
  push_image:
    docker:
      image: docker:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "Logging into OCI Container Registry using Security Token..."
      - oci --auth security_token --security-token eyJraWQiOiJhc3dfaWFkXzE3MTU2NDgwNzIzNzciLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvY2lkMS51c2VyLm9jMS4uYWFhYWFhYWFzd3VhamRrM2ZndGVydzNnZG92dGxqd2gzYzdid2J3dGV2MzRudTZ2Y3d4YmxrN3RhbHlhIiwiaXNzIjoiYXV0aFNlcnZpY2Uub3JhY2xlLmNvbSIsInNhbWxfZnJpbnQiOiI2NDpzMzk6MjQ6ZmM6YmI6MGQ6NDE6ZTg6ZjA6MjM6NWQ6MzU6ODA6Mjg6MjI6ODMiLCJwdHlwZSI6InVzZXIiLCJzZXNzX2V4cCI6IlNhdCwgMjMgTm92IDIwMjQgMjA6MTc6MzYgVVRDIiwiYXVkIjoib2NpIiwicHN0eXBlIjoibmF0ZiIsInR0eXBlIjoic2FtbGMiLCJleHAiOjE3MzIzNzI4MDcsImlhdCI6MTczMjM2OTIwNywianRpIjoiZDE1M2JmNDItODJiYS00NjM3LWFhM2EtOGZkOTFkZGE4MThmIiwidGVuYW50Ijoib2NpZDEudGVuYW5jeS5vYzEuLmFhYWFhYWFhZ2tiemdnNmxwenJmNDd4enk0cmpveGc0ZGU2bmNmaXEycm5jbWppdWp2eTJoamd4dnppcSIsImlzX2ZlZCI6InRydWUiLCJncnBzIjoiIiwiandrIjoie1wia2lkXCI6XCJJZ25vcmVkXCIsXCJuXCI6XCJ2MV95U3hLdGxwODdrYi1hTTRDeDZ1dmIyU1UxZHZnOWVVTC1HallTSGJnT2gzcy1DYi1PZl80cWFDS1dsMXVkei1za1p3ZUhsdlU1NkRBMUoxaXpiT0NNSUxNRmhCYlRJSWZFQlJPYWNhTHRaVldQNGFDM3JDRVN5WFJZeDRCLUJ2ZFVUd2tuRk1CcnVDMVYzWkpCMU5ka1ZOUWlMQVZVZGN3clJWdU9ZMlg5djBtNXZPaUx4UlhzM0NxUFR4cnpsekJTY0E5LThFaFRqMDNPWVRrbkNOYmcxY1BMZ2tQMFJ1aFJSQl9haDlwVWRDejR5WGVsaWhfM2habDNaamplTmZ1MkVyLXJhWVNGMzUxbTVUcU9wX2MtZ0pZOHY1RW9zcThNQVhkQ2FvdkZGVmRJeWEtR2d5N1R0OU5uRWxGMWhxdm9XWUYzcTFlMk93a3JmRlExWlFcIixcImVcIjpcIkFRQUJcIixcImt0eVwiOlwiUlNBXCIsXCJ1c2VcIjpudWxsfSJ9.RQM0rTkAaefI752J8rxW2UfRYHoeWsiYD8xGnAM5MgXiGS2gMF_p_B1R4Z66td1EgDomNzGp65RoTBk4CRfXmWpyFz8q0dFFUZz8imXubrRaJojBxLJqBwCqy8Eh8yUFOGqL2KHsjCZVP8aZ6pgwJ1h0zK3dnngirM1hfPOvB1z8-b1V_SNJEHIMmo_p2zOgPUZk0Tn77ugjmp5n28RcHF6dzWUUzdibtyRA1J5Su3a4ZgYDbuLdcvQpo5iJDMXVvLx-6obx-Ll9GfOmfJqDo2W9n1OC9tSaRatAFNYl8llUDrITOf7cpI-Y-m1IWna5SXiu_KHdGdzThh7V2OeZGw login iad.ocir.io
      - echo "Pushing Docker image to OCI Container Registry..."
      - docker push iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest
      - docker push iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:${GITHUB_SHA}

  # Job to deploy the image to an existing OCI Function
  deploy_function:
    docker:
      image: oci/oci-cli:latest
    commands:
      - echo "Updating Docker image for existing OCI Function..."
      # Here we update the function to use the newly pushed image
      - oci fn function update --compartment-id ocid1.compartment.oc1..aaaaaaaai7lpqrjb65oxp7yot4cdlgahobld5xpizdyjyaoef2tjunipxhpa --function-id ocid1.fnfunc.oc1.iad.aaaaaaaajmotp4ycz5pms3y4q3zqdxra6fyg53fxu2ap36yvqoglkbjwxmka --image iad.ocir.io/idlcbf4ihtx7/test-a/test-one/image-file:latest
      - echo "Creating or updating HTTP trigger for function..."
      # Create or update an HTTP trigger
      - oci fn trigger create \
          --compartment-id ocid1.compartment.oc1..aaaaaaaai7lpqrjb65oxp7yot4cdlgahobld5xpizdyjyaoef2tjunipxhpa \
          --function-id ocid1.fnfunc.oc1.iad.aaaaaaaajmotp4ycz5pms3y4q3zqdxra6fyg53fxu2ap36yvqoglkbjwxmka \
          --name my-http-trigger \
          --type http
      - echo "Function is successfully deployed and ready to receive HTTP requests."
      - oci fn function invoke --function-id ocid1.fnfunc.oc1.iad.aaaaaaaajmotp4ycz5pms3y4q3zqdxra6fyg53fxu2ap36yvqoglkbjwxmka --body '{}'

workflows:
  version: '1.0'
  pipeline:
    jobs:
      - build_image
      - push_image:
          requires:
            - build_image
      - deploy_function:
          requires:
            - push_image
